name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  # Permette di avviare il deploy anche a mano dal tab "Actions"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Usiamo "npm install" perché non hai package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_VISION_API_KEY: ${{ secrets.VISION_API_KEY }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIQUIDAZIONE_EREDI }}"
          channelId: live
          projectId: liquidazione-eredi

